#!/bin/bash

LOG_LEVEL=error
#RUSTUP_TOOLCHAIN=nightly-2019-11-13
RUSTUP_TOOLCHAIN=nightly
RUST_VERSION=${RUSTUP_TOOLCHAIN}-x86_64-unknown-linux-gnu
COMPILER_PATH=$HOME/.rustup/toolchains/${RUST_VERSION}
TARGET_PATH="./stainless_driver/target/debug"
LIB_PATH="${COMPILER_PATH}/lib:${TARGET_PATH}:${TARGET_PATH}/deps"
RUSTC_EXPORT="${TARGET_PATH}/rustc_to_stainless"

LD_LIBRARY_PATH=${LIB_PATH} \
RUST_LOG=${LOG_LEVEL} \
${RUSTC_EXPORT} \
  -L ${COMPILER_PATH}/lib/rustlib/x86_64-unknown-linux-gnu/lib/ \
  "$@"