#!/usr/bin/env bash
set +e

function check_installed () {
  if ! [ -x "$(command -v ${1})" ]; then
    echo "Error: Could not find ${1}." >&2
    exit 1
  fi
}

check_installed "rustup"

SELF_DIR="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

RUSTUP_TOOLCHAIN_VERSION=nightly
RUSTUP_HOME="$( rustup run ${RUSTUP_TOOLCHAIN_VERSION} printenv RUSTUP_HOME )"
RUSTUP_TOOLCHAIN="$( rustup run ${RUSTUP_TOOLCHAIN_VERSION} printenv RUSTUP_TOOLCHAIN )"
RUSTUP_TOOLCHAIN_ARCH="${RUSTUP_TOOLCHAIN#*-}"

LOG_LEVEL=error
SYSROOT_PATH="${RUSTUP_HOME}/toolchains/${RUSTUP_TOOLCHAIN}"
TARGET_PATH="${SELF_DIR}/../target/debug"
RUSTC_EXPORT="${TARGET_PATH}/rustc_to_stainless"

if [ ! -f "${RUSTC_EXPORT}" ]; then
  echo "Error: Could not find ${RUSTC_EXPORT}."
  exit 1
fi

RUST_LOG=${LOG_LEVEL} \
rustup run ${RUSTUP_TOOLCHAIN_VERSION} ${RUSTC_EXPORT} \
  --sysroot ${SYSROOT_PATH} \
  "$@"
